// Theme: darkTheme
export const darkTheme = {
  colors: {
    global: {
      backgroundPrimary: "#393941",
      backgroundSecondary: "#28282e",
      borderPrimary: "#4d5e80",
      borderSecondary: "#6b7a99",
      textPrimary: "#ffffff",
      textSecondary: "#f7f8fa",
      icon: "#edeff2",
      iconActive: "#f7f8fa",
    },
    formComponents: {
      inputBoxHover: "#7cf0f4",
      inputBoxFocus: "#a1f4f7",
      inputBoxBorderFocus: "#bfbfc5",
      tickBoxBorder: "#6b7a99",
      tickBoxChecked: "#008ba3",
      tickBoxCheckedHover: "#00687a",
      tickBoxUnchecked: "#edeff2",
      tickBoxUncheckedHover: "#c3cad9",
      tickBoxSVG: "#f1f1f1",
      indicatorGreen: "#74e660",
      indicatorAmber: "#f3af4a",
      indicatorRed: "#ee482a",
    },
    patientList: {
      header: "#4d5e80",
      rowOdd: "#e6e9ef",
      rowHover: "#6a7ca0",
    },
    incomingPatientsList: {
      header: "#008ba3",
      rowOdd: "#deedf2",
      rowHover: "#509fb9",
    },
    reportEntry: {
      alerts: "#ff6347",
      allergies: "#ffaf85",
      complaint: "#5398be",
      complications: "#9bc53d",
      diagnosis: "#ba2c73",
      findings: "#1b998b",
      procedures: "#585481",
      symptoms: "#2978a0",
      noThemeEntered: "#3a3a40",
    },
  },
};
